### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by sitxxar** [Widiskel/grass-node-bot#1]
![image](https://github.com/user-attachments/assets/69cda521-6bf9-4a17-9bff-65413ab60e74)

**Comment by unot58** [comment]
![Screenshot_2024-11-06-15-20-13-023_com server auditor ssh client](https://github.com/user-attachments/assets/f1972d02-d651-4692-b80c-3d478647464b)

**Comment by unot58** [comment]
help me please

**Comment by Widiskel** [comment]
> help me please

npm install, and make sure use node js v22

**Comment by sitxxar** [comment]
Already use nodejs v22

Pada Kam, 7 Nov 2024 2.20 AM, Widianto Eka saputro ***@***.***>
menulis:
